

// This macro reads ROIs from text files (generated by YOLOv5) and generates roiset.zip based on stack dimensions below.
// The input folder should consist of multiple sub-folders, and each sub-folder should consist of a folder named
// as "labels" which contains multiple text files.
// The last 2 digit in the text file name, xx.txt is the z, starting from 0.
//
// Written by hui ting, 5 May 2021.


////////////////////////////////////////    Stack dimensions    ////////////////////////////////////////////////////////

img_w = 2048;
img_h = 2048;
zslices = 50;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


path_main = getDirectory("Select main folder");
res_folder = getDirectory("Select results folder");

folders = getFileList(path_main);
total_folders = folders.length;

newImage("blank", "8-bit grayscale-mode", img_w, img_h, 1, zslices, 1);
roiManager("reset");

for (ifolder = 0; ifolder < total_folders; ifolder++) {

	if (endsWith(folders[ifolder],"/")){

	path_folder = path_main+folders[ifolder];	
	pathname = path_folder+"labels";
	print(pathname);

	list = getFileList(pathname); // text files

for (ifile = 0; ifile < list.length; ifile++) {

	if (endsWith(list[ifile], ".txt")){
		
filename = list[ifile];

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

z_txt = substring(filename, lengthOf(filename)-6, lengthOf(filename)-4); // last 2 digit xx.txt is the z

if (parseInt(substring(z_txt,0,1))==0) // if is 00.txt to 09.txt ...
   z_txt_no = parseInt(substring(z_txt,1,2));
else {
   z_txt_no = parseInt(substring(z_txt,0,2));
}

z_current = z_txt_no+1;


//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


filestring=File.openAsString(pathname+File.separator+filename);

rows=split(filestring, "\n"); // rows[i] = i-th row
total_rows = rows.length;

class=newArray(total_rows);
xc_n=newArray(total_rows);
yc_n=newArray(total_rows);
w_n=newArray(total_rows);
h_n=newArray(total_rows);

for(i=0; i<total_rows; i++){
	
    columns=split(rows[i]," ");  // columns[0] = class (Always 0)

    class[i]=parseFloat(columns[0]);
	xc_n[i]=parseFloat(columns[1]);
	yc_n[i]=parseFloat(columns[2]);
	w_n[i]=parseFloat(columns[3]);
	h_n[i]=parseFloat(columns[4]);


    w_bb = round(img_w*w_n[i]);
    h_bb = round(img_h*h_n[i]);
    
    xc = xc_n[i]*img_w;
    xmin_bb = round(xc-(0.5*w_bb));

    yc = yc_n[i]*img_h;
    ymin_bb = round(yc-(0.5*h_bb));

	Stack.setPosition(1, z_current, 1);
	makeRectangle(xmin_bb, ymin_bb, w_bb, h_bb);
	Roi.setPosition(z_current);
	Roi.setGroup(class[i]);
	roiManager("Add");

}

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	}
}

run("Select None");
outname = substring(filename,0,lengthOf(filename)-8);
roiManager("Save", res_folder+File.separator+outname+".zip");
roiManager("List");
saveAs("Results", res_folder+File.separator+outname+".csv");
run("Close");
roiManager("reset");

	}
}


